# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dclop\PycharmProjects\pySpeedTester\speed.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 410, 621, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.downloadBar.setStyleSheet("\n"
"background-color: rgb(35, 174, 227);")
        self.downloadBar.setProperty("value", 0)
        self.downloadBar.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadBar.setObjectName("downloadBar")
        self.horizontalLayout.addWidget(self.downloadBar)
        self.uploadBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.uploadBar.setStyleSheet("\n"
"background-color: rgb(22, 106, 153);")
        self.uploadBar.setProperty("value", 0)
        self.uploadBar.setAlignment(QtCore.Qt.AlignCenter)
        self.uploadBar.setObjectName("uploadBar")
        self.horizontalLayout.addWidget(self.uploadBar)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 611, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 170, 131, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(61, 179, 158);")
        self.label_4.setLineWidth(0)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.downSpeed = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.downSpeed.setStyleSheet("color: rgb(61, 179, 158);")
        self.downSpeed.setObjectName("downSpeed")
        self.verticalLayout_2.addWidget(self.downSpeed)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("\n"
"color: rgb(61, 179, 158);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 170, 131, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(61, 179, 158);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.upSpeed = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.upSpeed.setStyleSheet("color: rgb(61, 179, 158);")
        self.upSpeed.setObjectName("upSpeed")
        self.verticalLayout_3.addWidget(self.upSpeed)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(53, 177, 155);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(270, 120, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.goButton.setFont(font)
        self.goButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.goButton.setObjectName("goButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(360, 120, 41, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.resetButton.setObjectName("resetButton")
        self.backgroundImage = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImage.setGeometry(QtCore.QRect(-4, -8, 641, 481))
        self.backgroundImage.setText("")
        self.backgroundImage.setPixmap(QtGui.QPixmap("C:\\Users\\dclop\\PycharmProjects\\pySpeedTester\\../../Pictures/aiphoto.jpg"))
        self.backgroundImage.setScaledContents(True)
        self.backgroundImage.setIndent(0)
        self.backgroundImage.setObjectName("backgroundImage")
        self.speedDownBack = QtWidgets.QLabel(self.centralwidget)
        self.speedDownBack.setGeometry(QtCore.QRect(80, 160, 151, 131))
        self.speedDownBack.setText("")
        self.speedDownBack.setPixmap(QtGui.QPixmap("C:\\Users\\dclop\\PycharmProjects\\pySpeedTester\\../../Pictures/speedImage.png"))
        self.speedDownBack.setScaledContents(True)
        self.speedDownBack.setObjectName("speedDownBack")
        self.goButtonBack = QtWidgets.QLabel(self.centralwidget)
        self.goButtonBack.setGeometry(QtCore.QRect(230, 90, 101, 81))
        self.goButtonBack.setText("")
        self.goButtonBack.setPixmap(QtGui.QPixmap("C:\\Users\\dclop\\PycharmProjects\\pySpeedTester\\../../Pictures/button.png"))
        self.goButtonBack.setObjectName("goButtonBack")
        self.resetButtonBack_2 = QtWidgets.QLabel(self.centralwidget)
        self.resetButtonBack_2.setGeometry(QtCore.QRect(330, 90, 101, 81))
        self.resetButtonBack_2.setText("")
        self.resetButtonBack_2.setPixmap(QtGui.QPixmap("C:\\Users\\dclop\\PycharmProjects\\pySpeedTester\\../../Pictures/button.png"))
        self.resetButtonBack_2.setObjectName("resetButtonBack_2")
        self.upSpeedBack = QtWidgets.QLabel(self.centralwidget)
        self.upSpeedBack.setGeometry(QtCore.QRect(450, 160, 151, 131))
        self.upSpeedBack.setText("")
        self.upSpeedBack.setPixmap(QtGui.QPixmap("C:\\Users\\dclop\\PycharmProjects\\pySpeedTester\\../../Pictures/speedImage.png"))
        self.upSpeedBack.setScaledContents(True)
        self.upSpeedBack.setObjectName("upSpeedBack")
        self.backgroundImage.raise_()
        self.upSpeedBack.raise_()
        self.resetButtonBack_2.raise_()
        self.goButtonBack.raise_()
        self.speedDownBack.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.goButton.raise_()
        self.resetButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PySpeedTracker"))
        self.label.setText(_translate("MainWindow", "Checking Upload Speeds"))
        self.label_2.setText(_translate("MainWindow", "Checking Download Speeds"))
        self.label_3.setText(_translate("MainWindow", "Python ISP Speed Checker"))
        self.label_4.setText(_translate("MainWindow", "Download"))
        self.label_6.setText(_translate("MainWindow", "MB/S"))
        self.label_5.setText(_translate("MainWindow", "Upload"))
        self.label_7.setText(_translate("MainWindow", "MB/S"))
        self.goButton.setText(_translate("MainWindow", "GO!"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
